const STORE_PROJECTS_DATA = 'STORE_PROJECTS_DATA';
const STORE_WORK_DATA = 'STORE_WORK_DATA';
const STORE_EDUCATION_DATA = 'STORE_EDUCATION_DATA';
const PROJECTS_ERROR = 'PROJECTS_ERROR';

export {
	STORE_PROJECTS_DATA,
	STORE_EDUCATION_DATA,
	STORE_WORK_DATA,
	PROJECTS_ERROR
};
