const STORE_SLR_FLOW_INFO_SUCCESS = 'STORE_SLR_FLOW_INFO_SUCCESS';
const SELF_ENROLLMENT_ERROR = 'SELF_ENROLLMENT_ERROR';
const GET_SAVINGS_CHART_INFO_SUCCESS = 'GET_SAVINGS_CHART_INFO_SUCCESS';

export {
	STORE_SLR_FLOW_INFO_SUCCESS,
	SELF_ENROLLMENT_ERROR,
	GET_SAVINGS_CHART_INFO_SUCCESS
};
